import type { Metadata } from "next";
import AdminNavigation from "./_components/admin-navigation";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      {/* <Suspense> */}
      <AdminNavigation>{children}</AdminNavigation>
      {/* </Suspense> */}
    </main>
  );
}
