import type { Metadata } from "next";
import AdminNavigation from "./_components/admin-navigation";

export const metadata: Metadata = {
  title: "London Home Safety Limited | Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <AdminNavigation>{children}</AdminNavigation>
    </main>
  );
}
