import * as React from "react";
import Header from "../_components/global/header/header";
import Footer from "../_components/global/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout(props: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>{props.children}</main>
      <Footer />
    </>
  );
}
